//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockMovement
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public decimal LowPrice { get; set; }
        public decimal HighPrice { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
