//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBridge.BuldingBlocks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopBridge.BuldingBlocks.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit of the characters allowed..
        /// </summary>
        public static string Common_Limit_Error {
            get {
                return ResourceManager.GetString("Common_Limit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string Common_No_Record_Found {
            get {
                return ResourceManager.GetString("Common_No_Record_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product deleted successfully..
        /// </summary>
        public static string Product_Deleted_Successfully {
            get {
                return ResourceManager.GetString("Product_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price is required..
        /// </summary>
        public static string Product_High_Price_Required {
            get {
                return ResourceManager.GetString("Product_High_Price_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product low price is required..
        /// </summary>
        public static string Product_Low_Price_Required {
            get {
                return ResourceManager.GetString("Product_Low_Price_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found..
        /// </summary>
        public static string Product_NotFound {
            get {
                return ResourceManager.GetString("Product_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price should be grater than 0..
        /// </summary>
        public static string Product_Price_Zero_Validation {
            get {
                return ResourceManager.GetString("Product_Price_Zero_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required..
        /// </summary>
        public static string Product_ProductName_Required {
            get {
                return ResourceManager.GetString("Product_ProductName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quantity is required..
        /// </summary>
        public static string Product_Quantity_Required {
            get {
                return ResourceManager.GetString("Product_Quantity_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product saved successfully..
        /// </summary>
        public static string Product_Saved_Successfully {
            get {
                return ResourceManager.GetString("Product_Saved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product SKU already exists..
        /// </summary>
        public static string Product_SKU_Already_Exists {
            get {
                return ResourceManager.GetString("Product_SKU_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product id..
        /// </summary>
        public static string Productd_Invalid_ProductId {
            get {
                return ResourceManager.GetString("Productd_Invalid_ProductId", resourceCulture);
            }
        }
    }
}
